### ISSUE TITLE
feat: add a package to zoom in on images (but not logo or hero image on homepage)

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1193]

**Comment by jcstein** [comment]
[tested with custom css](https://www.loom.com/share/d8e56efb440c43a396240f690ba13420?sid=1b7c9951-b9ac-4a5b-862f-c85238cf3fe7)

```css
img:hover {
  transform: scale(1.2);
  transition: transform .2s ease-in-out;
}
```
