### ISSUE TITLE
docs: create guide for mounting keys to Docker images

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#402]
One of the modular fellows was asking a while back how to mount keys to a Docker image, at the time we recommended to build from source. In the past few weeks, there have been more requests to understand how to do this with Docker images on Celestia. This guidance will be particularly helpful for teams launching larger networks of Celestia nodes to power their projects.

- [ ] Create documentation to mount 1 key to a docker image (light node)

## Example instructions from @sysrex:

“I mount a volume inside the docker container and i set the node store there

```yaml
      volumes:
        - /opt/validator2/data/full:/root:rw
```

like this^ and the start cmd is:

```yaml
      command: [
              "celestia", "full",
              "--node.store", "/root/.celestia-full",
```

## Example `docker-compose.yml` from Sysrex

```yaml
version: '3.3'
​
networks:
  celestia:
    ipam:
      driver: default
      config:
        - subnet: 172.27.10.0/24
​
services:
  validator1:
    container_name: validator
    image: sysrex/validator:v0.11.0
    ports:
      - "1317:1317"
      - "9090:9090"
      - "26656:26656"
      - "26657:26657"
    command: [
      "start",
      "--moniker", "validator1",
      "--rpc.laddr", "tcp://0.0.0.0:26657"
    ]
    volumes:
      - ${PWD}/config/validator1/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/config/validator1/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/config/validator1/keyring-test:/opt/keyring-test:ro
      - ${PWD}/config/config.toml:/opt/config/config.toml:ro
      - ${PWD}/config/genesis.json:/opt/config/genesis.json:ro
      - /opt/validator1/data/app:/opt/data:rw
    networks:
      celestia:
        ipv4_address: 172.27.10.9
  bridge:
    container_name: bridge
    image: sysrex/celestia-node:v0.6.2-alex
    ports:
      - "2121:2121"
      - "6000:6000"
      - "26658:26658"
    environment:
      - NODE_TYPE=bridge
      - CELESTIA_CUSTOM=arabica-2:04EE55B212745B88F29943D7B9528C415473A211F12EEF6E9333EF32E4DEAF3C
    command: [
            "celestia", "bridge",
            "--node.store", "/root/.celestia-bridge",
            "start",
            "--core.ip",
            "172.27.10.9",
            "--core.rpc.port",
            "26657"
             ]
    volumes:
       - /opt/validator1/data/bridge:/root:rw
    networks:
      celestia:
        ipv4_address: 172.27.10.10
```

**Comment by jcstein** [comment]
From ChatGPT:

To mount a folder to a Docker image, you can use the -v flag when running the docker run command. The format for the flag is -v host-directory:container-directory, where host-directory is the path to the folder on the host machine and container-directory is the path where the folder should be mounted within the container. For example, to mount a folder located at /my/host/folder to the /my/container/folder directory within a container, you would use the following command:

```sh
docker run -v /my/host/folder:/my/container/folder -it my-image
```

This will allow the host folder to be accessible inside the container and any changes made inside container to reflect outside the container.

**Comment by jcstein** [comment]
In progress:

PWD = `docker-compose-test`

`docker-compose.yaml`
```yaml
version: '3.8'
services:
  celestia:
    image: ghcr.io/celestiaorg/celestia-node:0.6.2
    environment:
      - NODE_TYPE=light
    command: celestia light start --core.ip https://rpc-mocha.pops.one --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network mocha --keyring.accname my_celes_key
    volumes:
      - ${PWD}/keys:/root/.celestia-light-mocha/keys:ro
```

Mounts a (manually placed) `keys` directory from the PWD (contains `/keys` and `docker-compose.yml`) to the node store.

In 1 terminal from the PWD:

```bash
docker-compose up
```

In another terminal from PWD (being in PWD is not required, though):

```bash
docker ps
```

Copy the `CONTAINER ID` and then run:

```bash
docker exec -ti 22219541ffb0 /bin/bash
```

Attempt to `make cel-key` within the image, but it does not build (expected, as the source files are not in the container)

Result:
```bash
docker exec -ti 22219541ffb0 /bin/bash
root@22219541ffb0:/# make cel-key
bash: make: command not found
```

**Comment by jcstein** [comment]
linked discussion: https://github.com/celestiaorg/celestia-node/issues/1621

**Comment by jcstein** [comment]
# Docker with `cel-key`
First, build the Docker image by running this from the `celestia-node/` directory on [this branch](https://github.com/jcstein/celestia-node/tree/jcs/docker-cel-key):
```bash
docker build . -t celestia-node -f docker/Dockerfile
```
Now, run the image:
```bash
docker run -e NODE_TYPE=light -e P2P_NETWORK=mocha -p 26659:26659 celestia-node celestia light start --core.ip https://rpc-mocha.pops.one --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network mocha
```
List active containers in another window with:
```bash
docker ps
```
The response will look like:
```bash
CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS          PORTS      NAMES
<container_id>   celestia-node   "/entrypoint.sh cele…"   22 seconds ago   Up 21 seconds   2121/tcp   docker-compose-test-celestia-1
```
Interact with the container by replacing <container_id> for the container ID:
```bash
docker exec -ti <container_id> /bin/bash
```
Now, interact with `cel-key` to check for the key that was autogenerated when you started the node:
```bash
./cel-key list --keyring-backend test --node.type light
```

> This portion is not working at the moment:

To check the balance of your node, first you'll need the IP address:
```bash
container_id=$(docker ps | grep celestia-node | awk '{print $1}')
container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
echo $container_ip
```
Then, check the balance:
```bash
curl -X GET http://$container_ip:26659/balance
```
You can also export your key from the container. In the next section, you'll learn how to mount existing keys to the container.

## Mounting existing keys to container
In this example, we'll be mounting an existing key to the container. This will mount the entire `/.celestia-light<p2p_network>/keys` directory to your image. Write a `docker-compose.yml`:
```yaml
version: '3.8'
services:
  celestia:
    image: celestia-node
    environment:
      - NODE_TYPE=light
    command: celestia light start --core.ip https://rpc-mocha.pops.one --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network mocha --keyring.accname my_celes_key
    volumes:
      - ${PWD}/keys:/root/.celestia-light-mocha/keys
    ports:
      - 26659:26659
```
Start the container by running the following command in the directory with your `docker-compose.yml`:
```bash
docker-compose up
```
List active containers in another window with:
```bash
docker ps
```
The response will look like:
```bash
CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS          PORTS      NAMES
<container_id>   celestia-node   "/entrypoint.sh cele…"   22 seconds ago   Up 21 seconds   2121/tcp   docker-compose-test-celestia-1
```
Interact with the container by replacing <container_id> for the container ID:
```bash
docker exec -ti <container_id> /bin/bash
```
Now, interact with `cel-key` to check your address matches the address you expect with the key you mounted:
```bash
root@<container_id>:/# ./cel-key list --keyring-backend test --node.type light
using directory:  ~/.celestia-light-mocha/keys
- address: celestia1wkhyhr7ngf0ayqlpnsnxg4d72hfs5453dvunm9
  name: my_celes_key
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A1/NsoY0RGL7Hqt4VWLg441GQKJsZ2fBUnZXipgns8oV"}'
  type: local
```
